export const betaCopy = {
  en: {
    freshness: "Source observation age at first result display",
    live: "Live",
    under1h: "Under 1h (not live)",
    under24h: "1h–under 24h",
    stale: "Stale",
    unknownAge: "Unknown age",
    empty: "No results / successful requests",
    failure: "Failed / completed requests",
    cancelled: "Cancelled",
    pending: "Pending",
    title: "Local test metrics — not Beta results",
    decision: "Request → navigation click, median (not app launch)",
    exposed: "Searches shown",
    clicks: "Search → navigation click",
    handoffs: "Map handoff accepted (not arrival)",
    unknown: "No eligible sample",
    truncated: "Earlier attempts discarded: this is an incomplete window.",
  },
  fr: {
    freshness: "Âge de l’observation source au premier affichage",
    live: "En direct",
    under1h: "Moins de 1h (pas en direct)",
    under24h: "1h–moins de 24h",
    stale: "Périmé",
    unknownAge: "Âge inconnu",
    empty: "Sans résultat / requêtes réussies",
    failure: "Échecs / requêtes terminées",
    cancelled: "Annulées",
    pending: "En attente",
    title: "Mesures de test locales — pas de résultats bêta",
    decision: "Requête → clic de navigation, médiane (pas le lancement)",
    exposed: "Recherches affichées",
    clicks: "Recherche → clic de navigation",
    handoffs: "Ouverture de carte acceptée (pas une arrivée)",
    unknown: "Aucun échantillon admissible",
    truncated: "Anciennes tentatives supprimées : fenêtre incomplète.",
  },
  es: {
    freshness: "Edad de la observación de origen al primer mostrar",
    live: "En directo",
    under1h: "Menos de 1h (no en directo)",
    under24h: "1h–menos de 24h",
    stale: "Obsoleto",
    unknownAge: "Edad desconocida",
    empty: "Sin resultados / solicitudes correctas",
    failure: "Fallidas / solicitudes completadas",
    cancelled: "Canceladas",
    pending: "Pendientes",
    title: "Métricas de prueba locales — no son resultados beta",
    decision: "Solicitud → clic de navegación, mediana (no desde el inicio)",
    exposed: "Búsquedas mostradas",
    clicks: "Búsqueda → clic de navegación",
    handoffs: "Apertura del mapa aceptada (no es una llegada)",
    unknown: "Sin muestra válida",
    truncated: "Intentos anteriores eliminados: ventana incompleta.",
  },
} as const;
