import type { Language } from "../i18n/preferences";
const translations = {
  filters: ["Sort and filters", "Tri et filtres", "Orden y filtros"],
  moreEvidence: [
    "Show service data and sources",
    "Afficher données et sources",
    "Mostrar datos y fuentes",
  ],
  lessEvidence: ["Hide detailed data", "Masquer les détails", "Ocultar detalles"],
  dataLimits: [
    "Some data is unknown; check the result details.",
    "Certaines données sont inconnues ; consultez les détails.",
    "Algunos datos son desconocidos; consulta los detalles.",
  ],
  openingChecked: [
    "Opening evaluated at",
    "Ouverture évaluée à",
    "Apertura evaluada a las",
  ],
  availabilityObserved: [
    "Availability observed at",
    "Disponibilité observée à",
    "Disponibilidad observada a las",
  ],
  staleData: [
    "Some evidence is stale. Verify before travelling.",
    "Certaines données sont anciennes. Vérifiez avant de partir.",
    "Algunos datos están desactualizados. Comprueba antes de salir.",
  ],
  missingData: [
    "Unknown data is not a guarantee of price, opening or availability.",
    "Une donnée inconnue ne garantit ni prix, ni ouverture, ni disponibilité.",
    "Los datos desconocidos no garantizan precio, apertura ni disponibilidad.",
  ],
  lowConfidence: [
    "Low-confidence evidence; confirmation is recommended.",
    "Données à faible confiance ; confirmation conseillée.",
    "Datos de baja confianza; se recomienda confirmar.",
  ],
  expiredLive: [
    "Live charging status has expired or has no valid timestamp; availability is shown as unknown.",
    "L’état de recharge en direct a expiré ou sa date est invalide ; disponibilité inconnue.",
    "El estado de recarga en directo caducó o su fecha no es válida; disponibilidad desconocida.",
  ],
  radius: ["Area searched (radius)", "Zone recherchée (rayon)", "Zona buscada (radio)"],
  expand: ["Expand search area", "Élargir la zone", "Ampliar la zona"],
  no_service_points_in_radius: [
    "No listed service points in the searched area. Change location or service.",
    "Aucun service répertorié dans la zone. Changez de lieu ou de service.",
    "No hay servicios registrados en la zona. Cambia de lugar o servicio.",
  ],
  no_comparable_prices: [
    "No comparable prices, not necessarily no nearby stations.",
    "Aucun prix comparable, mais des stations peuvent exister à proximité.",
    "No hay precios comparables; puede haber estaciones cercanas.",
  ],
  no_open_service_points: [
    "No points confirmed open by the published schedules.",
    "Aucun point confirmé ouvert selon les horaires publiés.",
    "Ningún punto confirmado abierto según los horarios publicados.",
  ],
  opening_status_unknown: [
    "Opening status is unknown; this does not mean every service is closed.",
    "Ouverture inconnue : cela ne signifie pas que tous les services sont fermés.",
    "Apertura desconocida; no significa que todos los servicios estén cerrados.",
  ],
  capability_unavailable: [
    "This decision is unavailable with current evidence.",
    "Cette décision est indisponible avec les données actuelles.",
    "Esta decisión no está disponible con los datos actuales.",
  ],
  no_matching_service_points: [
    "No service points match the selected filters.",
    "Aucun service ne correspond aux filtres choisis.",
    "Ningún servicio coincide con los filtros seleccionados.",
  ],
  network: [
    "Network unavailable. Check your connection and retry.",
    "Réseau indisponible. Vérifiez la connexion et réessayez.",
    "Red no disponible. Comprueba la conexión y reintenta.",
  ],
  timeout: [
    "The request timed out. You can retry.",
    "Le délai est dépassé. Vous pouvez réessayer.",
    "La solicitud tardó demasiado. Puedes reintentar.",
  ],
  rateLimited: [
    "Too many requests. Please wait before retrying.",
    "Trop de requêtes. Patientez avant de réessayer.",
    "Demasiadas solicitudes. Espera antes de reintentar.",
  ],
  serverError: [
    "The service is temporarily unavailable. Retry later.",
    "Le service est temporairement indisponible. Réessayez plus tard.",
    "Servicio temporalmente no disponible. Reintenta más tarde.",
  ],
  notFound: [
    "This service point no longer exists.",
    "Ce point de service n’existe plus.",
    "Este punto de servicio ya no existe.",
  ],
  invalidResponse: [
    "The service returned invalid data. Please return and try later.",
    "Le service a renvoyé des données invalides. Revenez et réessayez plus tard.",
    "El servicio devolvió datos inválidos. Vuelve e inténtalo más tarde.",
  ],
  requestError: [
    "This request could not be completed. Check your selection.",
    "Cette requête a échoué. Vérifiez votre sélection.",
    "No se pudo completar la solicitud. Comprueba tu selección.",
  ],
  refreshing: [
    "Refreshing results…",
    "Actualisation des résultats…",
    "Actualizando resultados…",
  ],
  cancelRequest: ["Cancel request", "Annuler la requête", "Cancelar solicitud"],
  diagnosticsNotice: [
    "Optional local test events: search, selection and navigation. No coordinates or uploads. Cleared after 15 minutes or when disabled.",
    "Événements de test locaux facultatifs : recherche, sélection, navigation. Aucune coordonnée ni transmission. Effacés après 15 minutes ou à la désactivation.",
    "Eventos de prueba locales opcionales: búsqueda, selección y navegación. Sin coordenadas ni envíos. Se borran a los 15 minutos o al desactivar.",
  ],
  diagnosticsOn: [
    "Enable local test events",
    "Activer les événements de test locaux",
    "Activar eventos de prueba locales",
  ],
  diagnosticsOff: [
    "Disable and clear test events",
    "Désactiver et effacer les événements",
    "Desactivar y borrar eventos",
  ],
  diagnosticsCount: [
    "Recorded events",
    "Événements enregistrés",
    "Eventos registrados",
  ],
  navigate: ["Navigate", "Itinéraire", "Cómo llegar"],
  navigationFailed: [
    "Could not open navigation. Please try again or choose another map app.",
    "Impossible d’ouvrir la navigation. Réessayez ou choisissez une autre application.",
    "No se pudo abrir la navegación. Reintenta o elige otra aplicación.",
  ],
  navigationDisabled: [
    "Navigation unavailable: closed listing or invalid destination.",
    "Navigation indisponible : lieu fermé ou destination invalide.",
    "Navegación no disponible: lugar cerrado o destino no válido.",
  ],
  map: ["View map", "Voir la carte", "Ver mapa"],
  mapNotice: [
    "Optional map: Apple Maps on iOS, Google Maps on Android. The map provider processes the viewed area. No location tracking is enabled.",
    "Carte facultative : Apple Maps sur iOS, Google Maps sur Android. Le fournisseur traite la zone affichée. Aucun suivi de position n’est activé.",
    "Mapa opcional: Apple Maps en iOS, Google Maps en Android. El proveedor procesa la zona visible. No se activa seguimiento de ubicación.",
  ],
  mapUnavailable: [
    "Map not configured for this build. The result list and external navigation remain available.",
    "Carte non configurée pour cette version. La liste et la navigation externe restent disponibles.",
    "Mapa no configurado para esta versión. La lista y la navegación externa siguen disponibles.",
  ],
  details: ["View details", "Voir les détails", "Ver detalles"],
  back: ["Back", "Retour", "Volver"],
  invalidPoint: [
    "This service point link is invalid.",
    "Ce lien de service est invalide.",
    "Este enlace de servicio no es válido.",
  ],
  lifecycle: ["Listing status", "État de la fiche", "Estado de la ficha"],
  active: ["Active listing", "Fiche active", "Ficha activa"],
  permanently_closed: [
    "Permanently closed",
    "Fermé définitivement",
    "Cerrado permanentemente",
  ],
  temporarily_closed: [
    "Temporarily closed",
    "Fermé temporairement",
    "Cerrado temporalmente",
  ],
  unverified: ["Unverified", "Non vérifié", "Sin verificar"],
  hours: ["Published opening hours", "Horaires publiés", "Horario publicado"],
  updated: ["Listing updated", "Fiche mise à jour", "Ficha actualizada"],
  washTypes: ["Wash services", "Types de lavage", "Tipos de lavado"],
  automatic_rollers: [
    "Automatic rollers",
    "Rouleaux automatiques",
    "Rodillos automáticos",
  ],
  automatic_touchless: [
    "Automatic touchless",
    "Automatique sans contact",
    "Automático sin contacto",
  ],
  high_pressure_self_service: [
    "Self-service pressure wash",
    "Haute pression en libre-service",
    "Alta presión autoservicio",
  ],
  hand_wash: ["Hand wash", "Lavage manuel", "Lavado a mano"],
  interior_cleaning: ["Interior cleaning", "Nettoyage intérieur", "Limpieza interior"],
  vacuum: ["Vacuum", "Aspirateur", "Aspirador"],
  airCost: ["Air fee", "Tarif de gonflage", "Tarifa de aire"],
  free: ["Free", "Gratuit", "Gratis"],
  paid: [
    "Paid; amount may be unknown",
    "Payant ; montant parfois inconnu",
    "De pago; importe posiblemente desconocido",
  ],
  workingStatus: ["Equipment status", "État de l’équipement", "Estado del equipo"],
  working: [
    "Working according to source",
    "Fonctionnel selon la source",
    "Operativo según la fuente",
  ],
  broken: ["Broken", "En panne", "Averiado"],
  temporarily_unavailable: [
    "Temporarily unavailable",
    "Temporairement indisponible",
    "Temporalmente no disponible",
  ],
  access: ["Access", "Accès", "Acceso"],
  public: ["Public", "Public", "Público"],
  customers_only: ["Customers only", "Réservé aux clients", "Solo clientes"],
  power: [
    "Maximum rated power (not delivered speed)",
    "Puissance nominale maximale (pas le débit réel)",
    "Potencia nominal máxima (no velocidad real)",
  ],
  connectors: ["Connectors", "Connecteurs", "Conectores"],
  evses: ["Charging points", "Points de charge", "Puntos de recarga"],
  liveCount: [
    "Available charging points",
    "Points de charge disponibles",
    "Puntos de recarga disponibles",
  ],
  chargePrice: [
    "Comparable charging tariff",
    "Tarif de recharge comparable",
    "Tarifa de recarga comparable",
  ],
  spainLive: [
    "Spain live availability is not enabled",
    "Disponibilité en direct non activée en Espagne",
    "Disponibilidad en directo no activada en España",
  ],
  ccs_combo_2: ["CCS Combo 2", "CCS Combo 2", "CCS Combo 2"],
  type_2: ["Type 2", "Type 2", "Tipo 2"],
  type_2_attached: ["Attached Type 2", "Type 2 attaché", "Tipo 2 fijo"],
  chademo: ["CHAdeMO", "CHAdeMO", "CHAdeMO"],
  domestic_socket: ["Domestic socket", "Prise domestique", "Enchufe doméstico"],
  tesla_eu: ["Tesla EU", "Tesla UE", "Tesla UE"],
  fuelTypes: ["Listed fuels", "Carburants répertoriés", "Combustibles registrados"],
  selectedFuel: ["Selected fuel", "Carburant choisi", "Combustible elegido"],
  stock: ["Fuel stock", "Stock du carburant", "Existencias de combustible"],
  outOfStock: ["Out of stock", "En rupture", "Agotado"],
  notOutOfStock: [
    "No shortage reported",
    "Aucune rupture signalée",
    "Sin desabastecimiento comunicado",
  ],
  fuelAvailability: [
    "Selected fuel offered",
    "Carburant choisi proposé",
    "Combustible elegido ofrecido",
  ],
  yes: ["Yes", "Oui", "Sí"],
  no: ["No", "Non", "No"],
  priceObserved: ["Price observation", "Observation du prix", "Observación del precio"],
  observed: ["Source observation", "Observation source", "Observación de la fuente"],
  published: ["Source publication", "Publication source", "Publicación de la fuente"],
  fetched: ["Retrieved", "Récupéré", "Recuperado"],
  source: ["Source / licence", "Source / licence", "Fuente / licencia"],
  confidence: ["Confidence", "Confiance", "Confianza"],
  freshness: ["Freshness", "Fraîcheur", "Actualidad"],
  high: ["High", "Élevée", "Alta"],
  medium: ["Medium", "Moyenne", "Media"],
  low: ["Low", "Faible", "Baja"],
  unknown: ["Unknown", "Inconnu", "Desconocido"],
  price: ["Price", "Prix", "Precio"],
  opening: ["Scheduled opening", "Ouverture selon horaires", "Apertura según horario"],
  availability: ["Service status", "État du service", "Estado del servicio"],
  open: ["Open", "Ouvert", "Abierto"],
  closed: ["Closed", "Fermé", "Cerrado"],
  closing_soon: ["Closing soon", "Ferme bientôt", "Cierra pronto"],
  opening_soon: ["Opening soon", "Ouvre bientôt", "Abre pronto"],
  available: [
    "Available according to source",
    "Disponible selon la source",
    "Disponible según la fuente",
  ],
  unavailable: ["Unavailable", "Indisponible", "No disponible"],
  liter: ["litre", "litre", "litro"],
  kilogram: ["kg", "kg", "kg"],
  use: ["use", "utilisation", "uso"],
  wash_program: ["wash programme", "programme de lavage", "programa de lavado"],
  membership: ["Membership required", "Adhésion requise", "Requiere membresía"],
  membershipUnknown: [
    "Membership conditions unknown",
    "Conditions d’adhésion inconnues",
    "Condiciones de membresía desconocidas",
  ],
  tax: ["Tax included", "Taxes incluses", "Impuestos incluidos"],
  noTax: ["Tax not included", "Hors taxes", "Impuestos no incluidos"],
  taxUnknown: ["Tax treatment unknown", "Taxes inconnues", "Impuestos desconocidos"],
  stale: ["Stale", "Ancien", "Desactualizado"],
  live: ["Live", "En direct", "En directo"],
  verified: ["Verified", "Vérifié", "Verificado"],
  recent: ["Recent", "Récent", "Reciente"],
} satisfies Record<string, [string, string, string]>;
export function evidenceCopy(language: Language) {
  const index = { en: 0, fr: 1, es: 2 }[language];
  return Object.fromEntries(
    Object.entries(translations).map(([key, values]) => [key, values[index]!]),
  ) as Record<keyof typeof translations, string>;
}
