import type { Language } from "../i18n/preferences";
const translations = {
  washTypes: ["Wash services", "Types de lavage", "Tipos de lavado"],
  automatic_rollers: [
    "Automatic rollers",
    "Rouleaux automatiques",
    "Rodillos automáticos",
  ],
  automatic_touchless: [
    "Automatic touchless",
    "Automatique sans contact",
    "Automático sin contacto",
  ],
  high_pressure_self_service: [
    "Self-service pressure wash",
    "Haute pression en libre-service",
    "Alta presión autoservicio",
  ],
  hand_wash: ["Hand wash", "Lavage manuel", "Lavado a mano"],
  interior_cleaning: ["Interior cleaning", "Nettoyage intérieur", "Limpieza interior"],
  vacuum: ["Vacuum", "Aspirateur", "Aspirador"],
  airCost: ["Air fee", "Tarif de gonflage", "Tarifa de aire"],
  free: ["Free", "Gratuit", "Gratis"],
  paid: [
    "Paid; amount may be unknown",
    "Payant ; montant parfois inconnu",
    "De pago; importe posiblemente desconocido",
  ],
  workingStatus: ["Equipment status", "État de l’équipement", "Estado del equipo"],
  working: [
    "Working according to source",
    "Fonctionnel selon la source",
    "Operativo según la fuente",
  ],
  broken: ["Broken", "En panne", "Averiado"],
  temporarily_unavailable: [
    "Temporarily unavailable",
    "Temporairement indisponible",
    "Temporalmente no disponible",
  ],
  access: ["Access", "Accès", "Acceso"],
  public: ["Public", "Public", "Público"],
  customers_only: ["Customers only", "Réservé aux clients", "Solo clientes"],
  power: [
    "Maximum rated power (not delivered speed)",
    "Puissance nominale maximale (pas le débit réel)",
    "Potencia nominal máxima (no velocidad real)",
  ],
  connectors: ["Connectors", "Connecteurs", "Conectores"],
  evses: ["Charging points", "Points de charge", "Puntos de recarga"],
  liveCount: [
    "Available charging points",
    "Points de charge disponibles",
    "Puntos de recarga disponibles",
  ],
  chargePrice: [
    "Comparable charging tariff",
    "Tarif de recharge comparable",
    "Tarifa de recarga comparable",
  ],
  spainLive: [
    "Spain live availability is not enabled",
    "Disponibilité en direct non activée en Espagne",
    "Disponibilidad en directo no activada en España",
  ],
  ccs_combo_2: ["CCS Combo 2", "CCS Combo 2", "CCS Combo 2"],
  type_2: ["Type 2", "Type 2", "Tipo 2"],
  type_2_attached: ["Attached Type 2", "Type 2 attaché", "Tipo 2 fijo"],
  chademo: ["CHAdeMO", "CHAdeMO", "CHAdeMO"],
  domestic_socket: ["Domestic socket", "Prise domestique", "Enchufe doméstico"],
  tesla_eu: ["Tesla EU", "Tesla UE", "Tesla UE"],
  fuelTypes: ["Listed fuels", "Carburants répertoriés", "Combustibles registrados"],
  selectedFuel: ["Selected fuel", "Carburant choisi", "Combustible elegido"],
  stock: ["Fuel stock", "Stock du carburant", "Existencias de combustible"],
  outOfStock: ["Out of stock", "En rupture", "Agotado"],
  notOutOfStock: [
    "No shortage reported",
    "Aucune rupture signalée",
    "Sin desabastecimiento comunicado",
  ],
  fuelAvailability: [
    "Selected fuel offered",
    "Carburant choisi proposé",
    "Combustible elegido ofrecido",
  ],
  yes: ["Yes", "Oui", "Sí"],
  no: ["No", "Non", "No"],
  priceObserved: ["Price observation", "Observation du prix", "Observación del precio"],
  observed: ["Source observation", "Observation source", "Observación de la fuente"],
  published: ["Source publication", "Publication source", "Publicación de la fuente"],
  fetched: ["Retrieved", "Récupéré", "Recuperado"],
  source: ["Source / licence", "Source / licence", "Fuente / licencia"],
  confidence: ["Confidence", "Confiance", "Confianza"],
  freshness: ["Freshness", "Fraîcheur", "Actualidad"],
  high: ["High", "Élevée", "Alta"],
  medium: ["Medium", "Moyenne", "Media"],
  low: ["Low", "Faible", "Baja"],
  unknown: ["Unknown", "Inconnu", "Desconocido"],
  price: ["Price", "Prix", "Precio"],
  opening: ["Scheduled opening", "Ouverture selon horaires", "Apertura según horario"],
  availability: ["Service status", "État du service", "Estado del servicio"],
  open: ["Open", "Ouvert", "Abierto"],
  closed: ["Closed", "Fermé", "Cerrado"],
  closing_soon: ["Closing soon", "Ferme bientôt", "Cierra pronto"],
  opening_soon: ["Opening soon", "Ouvre bientôt", "Abre pronto"],
  available: [
    "Available according to source",
    "Disponible selon la source",
    "Disponible según la fuente",
  ],
  unavailable: ["Unavailable", "Indisponible", "No disponible"],
  liter: ["litre", "litre", "litro"],
  kilogram: ["kg", "kg", "kg"],
  use: ["use", "utilisation", "uso"],
  wash_program: ["wash programme", "programme de lavage", "programa de lavado"],
  membership: ["Membership required", "Adhésion requise", "Requiere membresía"],
  membershipUnknown: [
    "Membership conditions unknown",
    "Conditions d’adhésion inconnues",
    "Condiciones de membresía desconocidas",
  ],
  tax: ["Tax included", "Taxes incluses", "Impuestos incluidos"],
  noTax: ["Tax not included", "Hors taxes", "Impuestos no incluidos"],
  taxUnknown: ["Tax treatment unknown", "Taxes inconnues", "Impuestos desconocidos"],
  stale: ["Stale", "Ancien", "Desactualizado"],
  live: ["Live", "En direct", "En directo"],
  verified: ["Verified", "Vérifié", "Verificado"],
  recent: ["Recent", "Récent", "Reciente"],
} satisfies Record<string, [string, string, string]>;
export function evidenceCopy(language: Language) {
  const index = { en: 0, fr: 1, es: 2 }[language];
  return Object.fromEntries(
    Object.entries(translations).map(([key, values]) => [key, values[index]!]),
  ) as Record<keyof typeof translations, string>;
}
